name: users_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  auto_route: ^9.3.0
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  shared_preferences: ^2.3.5
  logger: ^2.5.0
  json_annotation: ^4.9.0
  gap: ^3.0.1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  json_serializable: ^6.7.0
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true
